version: "3.7"

services:
  python: &python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - rabbitmq
      - celery_worker
  # rabbit message queue
  rabbitmq:
    image: rabbitmq:3.8-alpine
  # celery worker service
  celery_worker:
    <<: *python
    command: celery -A biodata worker --loglevel=info 
    ports: []
    depends_on:
      - rabbitmq