version: "3"

services:
  python: &python3.8
    image: python:3.8
    build:
      context: .
      dockerfile: 'app/docker/python/Dockerfile'
    volumes:
      - './app:/app'
    ports:
      - '8000:8000'
    depends_on:
      - 'rabbitmq'
      - 'celery_worker'

  # rabbit message queue
  rabbitmq:
    image: 'rabbitmq:3.7-alpine'
  celery worker service
  celery_worker:
    <<: *python
    command: 'ln -s /run/shm /dev/shm && celery -A biodata worker --loglevel=info'
    ports: []
    depends_on:
      - 'rabbitmq'
  