# Generated by Django 2.2.6 on 2019-10-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='date_of_birth',
            field=models.DateField(verbose_name='DoB'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
    ]
