# Generated by Django 2.2.9 on 2019-12-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_remove_biodata_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='address',
        ),
        migrations.AlterField(
            model_name='biodata',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date f Birth'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='date_of_employment',
            field=models.DateField(verbose_name='Date f Employment'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='salary',
            field=models.IntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='supervisors',
            field=models.CharField(editable=False, max_length=100, verbose_name='Supervisors'),
        ),
    ]
