# Generated by Django 2.2.9 on 2019-12-29 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0003_auto_20191229_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='supervisors',
        ),
        migrations.AlterField(
            model_name='biodata',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='date_of_employment',
            field=models.DateField(verbose_name='Date of Employment'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
